Fix urrlib3 errors in Prerequisites lambda
We see the following issues in the lambdas logs:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'index': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)
Traceback (most recent call last):
```

Seems this was bumped to v2.0.0, for now rolling back to v1.26.15.