Pin urrlib to 1.26.15 everywhere
We see the issue
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'index': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)
Traceback (most recent call last):
```
in multiple lambdas, e.g. the CopyZips one.

Thus, let's see if we can pin it for all lambdas.